import 'package:flight_app/constants/app_const.dart';
import 'package:flight_app/constants/img_api.dart';

class City {
  final String id;
  final String code;
  final String name;
  final String description;
  final List<String> photos;
  final double totalHotel;
  final double totalTransport;

  City({
    required this.id,
    required this.code,
    required this.name,
    required this.description,
    required this.photos,
    required this.totalHotel,
    required this.totalTransport,
  });
}

final List<City> cityList = [
  City(
    id: '1',
    code: 'KHI',
    name: 'Karachi',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[1]],
    totalHotel: 85,
    totalTransport: 30,
  ),
  City(
    id: '2',
    code: 'LHE',
    name: 'Lahore',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[2]],
    totalHotel: 92,
    totalTransport: 35,
  ),
  City(
    id: '3',
    code: 'ISB',
    name: 'Islamabad',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[16]],
    totalHotel: 78,
    totalTransport: 28,
  ),
  City(
    id: '4',
    code: 'RWP',
    name: 'Rawalpindi',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[4]],
    totalHotel: 65,
    totalTransport: 25,
  ),
  City(
    id: '5',
    code: 'PEW',
    name: 'Peshawar',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[5]],
    totalHotel: 55,
    totalTransport: 22,
  ),
  City(
    id: '6',
    code: 'QTA',
    name: 'Quetta',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[24]],
    totalHotel: 45,
    totalTransport: 20,
  ),
  City(
    id: '7',
    code: 'MUX',
    name: 'Multan',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[7]],
    totalHotel: 68,
    totalTransport: 26,
  ),
  City(
    id: '8',
    code: 'LYP',
    name: 'Faisalabad',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[8]],
    totalHotel: 72,
    totalTransport: 28,
  ),
  City(
    id: '9',
    code: 'HYD',
    name: 'Hyderabad',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[9]],
    totalHotel: 58,
    totalTransport: 24,
  ),
  City(
    id: '10',
    code: 'SKR',
    name: 'Sukkur',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[10]],
    totalHotel: 42,
    totalTransport: 18,
  ),
  City(
    id: '11',
    code: 'BWP',
    name: 'Bahawalpur',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[11]],
    totalHotel: 48,
    totalTransport: 20,
  ),
  City(
    id: '12',
    code: 'GJW',
    name: 'Gujranwala',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[12]],
    totalHotel: 52,
    totalTransport: 22,
  ),
  City(
    id: '13',
    code: 'SKT',
    name: 'Sialkot',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[19]],
    totalHotel: 46,
    totalTransport: 19,
  ),
  City(
    id: '14',
    code: 'SGD',
    name: 'Sargodha',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[28]],
    totalHotel: 38,
    totalTransport: 17,
  ),
  City(
    id: '15',
    code: 'SWL',
    name: 'Sahiwal',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[15]],
    totalHotel: 35,
    totalTransport: 16,
  ),
  City(
    id: '16',
    code: 'GWD',
    name: 'Gwadar',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[3]],
    totalHotel: 32,
    totalTransport: 15,
  ),
  City(
    id: '17',
    code: 'GIL',
    name: 'Gilgit',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[17]],
    totalHotel: 28,
    totalTransport: 14,
  ),
  City(
    id: '18',
    code: 'SKD',
    name: 'Skardu',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[18]],
    totalHotel: 25,
    totalTransport: 12,
  ),
  City(
    id: '19',
    code: 'MRE',
    name: 'Murree',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[13]],
    totalHotel: 55,
    totalTransport: 20,
  ),
  City(
    id: '20',
    code: 'NWB',
    name: 'Nawabshah',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[20]],
    totalHotel: 30,
    totalTransport: 15,
  ),
  City(
    id: '21',
    code: 'DBA',
    name: 'D.I. Khan',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[11]],
    totalHotel: 26,
    totalTransport: 13,
  ),
  City(
    id: '22',
    code: 'JAG',
    name: 'Jacobabad',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[22]],
    totalHotel: 22,
    totalTransport: 11,
  ),
  City(
    id: '23',
    code: 'CJL',
    name: 'Chitral',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[23]],
    totalHotel: 20,
    totalTransport: 10,
  ),
  City(
    id: '24',
    code: 'BNP',
    name: 'Bannu',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[6]],
    totalHotel: 18,
    totalTransport: 9,
  ),
  City(
    id: '25',
    code: 'TFT',
    name: 'Turbat',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[25]],
    totalHotel: 16,
    totalTransport: 8,
  ),
  City(
    id: '26',
    code: 'ZHB',
    name: 'Zhob',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[26]],
    totalHotel: 14,
    totalTransport: 7,
  ),
  City(
    id: '27',
    code: 'KDD',
    name: 'Khuzdar',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[27]],
    totalHotel: 12,
    totalTransport: 6,
  ),
  City(
    id: '28',
    code: 'MWD',
    name: 'Mianwali',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[14]],
    totalHotel: 10,
    totalTransport: 5,
  ),
  City(
    id: '29',
    code: 'RAZ',
    name: 'Rawalakot',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[29]],
    totalHotel: 24,
    totalTransport: 12,
  ),
  City(
    id: '30',
    code: 'ATK',
    name: 'Attock',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[30]],
    totalHotel: 15,
    totalTransport: 8,
  ),
  City(
    id: '31',
    code: 'LRK',
    name: 'Larkana',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[1]],
    totalHotel: 40,
    totalTransport: 18,
  ),
  City(
    id: '32',
    code: 'DGK',
    name: 'Dera Ghazi Khan',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[2]],
    totalHotel: 35,
    totalTransport: 16,
  ),
  City(
    id: '33',
    code: 'ABT',
    name: 'Abbottabad',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[3]],
    totalHotel: 45,
    totalTransport: 20,
  ),
  City(
    id: '34',
    code: 'MRD',
    name: 'Mardan',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[4]],
    totalHotel: 38,
    totalTransport: 17,
  ),
  City(
    id: '35',
    code: 'SWT',
    name: 'Swat',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[5]],
    totalHotel: 50,
    totalTransport: 22,
  ),
  City(
    id: '36',
    code: 'HNZ',
    name: 'Hunza',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[6]],
    totalHotel: 42,
    totalTransport: 19,
  ),
  City(
    id: '37',
    code: 'PSI',
    name: 'Pasni',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[7]],
    totalHotel: 20,
    totalTransport: 10,
  ),
  City(
    id: '38',
    code: 'PGR',
    name: 'Panjgur',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[8]],
    totalHotel: 18,
    totalTransport: 9,
  ),
  City(
    id: '39',
    code: 'DBN',
    name: 'Dalbandin',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[9]],
    totalHotel: 15,
    totalTransport: 8,
  ),
  City(
    id: '40',
    code: 'CHM',
    name: 'Chaman',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[10]],
    totalHotel: 22,
    totalTransport: 11,
  ),
];
