import 'package:flight_app/models/city.dart';
import 'package:flight_app/models/plane.dart';

class FlightPackage {
  final String id;
  final String img;
  final City from;
  final City to;
  final Plane plane;
  final double price;
  final double discount;
  final String? label;
  final bool hasRefund;
  final bool roundTrip;
  final List<String>? tags;
  final String date;

  FlightPackage({
    required this.id,
    required this.img,
    required this.from,
    required this.to,
    required this.date,
    required this.plane,
    required this.price,
    this.discount = 0,
    this.label,
    this.hasRefund = true,
    this.roundTrip = true,
    this.tags,
  });
}

// Consistent background image used across all flight featured package cards
const String _flightCardImg =
    'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80';

final List<FlightPackage> flightPackageList = [
  FlightPackage(
      id: '1',
      img: _flightCardImg,
      from: cityList[1],
      to: cityList[2],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '2',
      img: _flightCardImg,
      from: cityList[2],
      to: cityList[5],
      plane: planeList[2],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '3',
      img: _flightCardImg,
      from: cityList[3],
      to: cityList[4],
      plane: planeList[3],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '4',
      img: _flightCardImg,
      from: cityList[4],
      to: cityList[6],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '5',
      img: _flightCardImg,
      from: cityList[1],
      to: cityList[2],
      plane: planeList[4],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '6',
      img: _flightCardImg,
      from: cityList[6],
      to: cityList[7],
      plane: planeList[5],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '7',
      img: _flightCardImg,
      from: cityList[7],
      to: cityList[8],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '8',
      img: _flightCardImg,
      from: cityList[8],
      to: cityList[10],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '9',
      img: _flightCardImg,
      from: cityList[9],
      to: cityList[12],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '10',
      img: _flightCardImg,
      from: cityList[10],
      to: cityList[11],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '11',
      img: _flightCardImg,
      from: cityList[11],
      to: cityList[12],
      plane: planeList[3],
      price: 8500,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '12',
      img: _flightCardImg,
      from: cityList[12],
      to: cityList[15],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '13',
      img: _flightCardImg,
      from: cityList[13],
      to: cityList[14],
      plane: planeList[4],
      price: 8500,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '14',
      img: _flightCardImg,
      from: cityList[14],
      to: cityList[15],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '15',
      img: _flightCardImg,
      from: cityList[15],
      to: cityList[16],
      plane: planeList[0],
      price: 8000,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '16',
      img: _flightCardImg,
      from: cityList[16],
      to: cityList[18],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '17',
      img: _flightCardImg,
      from: cityList[17],
      to: cityList[18],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '18',
      img: _flightCardImg,
      from: cityList[18],
      to: cityList[19],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '19',
      img: _flightCardImg,
      from: cityList[20],
      to: cityList[22],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),
  FlightPackage(
      id: '20',
      img: _flightCardImg,
      from: cityList[20],
      to: cityList[24],
      plane: planeList[1],
      price: 800,
      discount: 10,
      label: '10% OFF',
      date: '17 - 19 Aug 2025',
      tags: ['limited promo', '10% OFF']),

  // ── KARACHI (KHI) ─ 8 packages ─────────────────────────────────────────
  FlightPackage(
    id: 'khi_lhe_1',
    img: _flightCardImg,
    from: cityList[0],
    to: cityList[1],
    plane: planeList[0],
    price: 14500,
    discount: 15,
    label: '15% OFF',
    date: '15 - 17 Apr 2026',
    tags: ['Best Seller', '15% OFF'],
  ),
  FlightPackage(
    id: 'khi_isb_1',
    img: _flightCardImg,
    from: cityList[0],
    to: cityList[2],
    plane: planeList[1],
    price: 16800,
    discount: 10,
    label: '10% OFF',
    date: '20 - 22 Apr 2026',
    tags: ['Capital Route', '10% OFF'],
  ),
  FlightPackage(
    id: 'khi_pew_1',
    img: _flightCardImg,
    from: cityList[0],
    to: cityList[4],
    plane: planeList[0],
    price: 18500,
    discount: 20,
    label: '20% OFF',
    date: '25 - 27 Apr 2026',
    tags: ['Northern Route', '20% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'khi_mux_1',
    img: _flightCardImg,
    from: cityList[0],
    to: cityList[6],
    plane: planeList[1],
    price: 11800,
    discount: 15,
    label: '15% OFF',
    date: '01 - 03 May 2026',
    tags: ['Promo Fare', '15% OFF'],
  ),
  FlightPackage(
    id: 'khi_qta_1',
    img: _flightCardImg,
    from: cityList[0],
    to: cityList[5],
    plane: planeList[2],
    price: 9500,
    discount: 10,
    label: '10% OFF',
    date: '05 - 07 May 2026',
    tags: ['Weekend Deal', '10% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'khi_lyp_1',
    img: _flightCardImg,
    from: cityList[0],
    to: cityList[7],
    plane: planeList[0],
    price: 13200,
    discount: 12,
    label: '12% OFF',
    date: '10 - 12 May 2026',
    tags: ['Early Bird', '12% OFF'],
  ),
  FlightPackage(
    id: 'khi_skt_1',
    img: _flightCardImg,
    from: cityList[0],
    to: cityList[12],
    plane: planeList[1],
    price: 15800,
    discount: 8,
    label: '8% OFF',
    date: '15 - 17 May 2026',
    tags: ['AirSial Route', '8% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'khi_gwd_1',
    img: _flightCardImg,
    from: cityList[0],
    to: cityList[15],
    plane: planeList[2],
    price: 8200,
    discount: 5,
    label: '5% OFF',
    date: '20 - 22 May 2026',
    tags: ['CPEC City', '5% OFF'],
  ),

  // ── LAHORE (LHE) ─ 8 packages ───────────────────────────────────────────
  FlightPackage(
    id: 'lhe_khi_1',
    img: _flightCardImg,
    from: cityList[1],
    to: cityList[0],
    plane: planeList[1],
    price: 14800,
    discount: 15,
    label: '15% OFF',
    date: '15 - 17 Apr 2026',
    tags: ['Best Seller', '15% OFF'],
  ),
  FlightPackage(
    id: 'lhe_isb_1',
    img: _flightCardImg,
    from: cityList[1],
    to: cityList[2],
    plane: planeList[8],
    price: 6800,
    discount: 10,
    label: '10% OFF',
    date: '20 - 22 Apr 2026',
    tags: ['Capital Route', '10% OFF'],
  ),
  FlightPackage(
    id: 'lhe_pew_1',
    img: _flightCardImg,
    from: cityList[1],
    to: cityList[4],
    plane: planeList[0],
    price: 9800,
    discount: 12,
    label: '12% OFF',
    date: '25 - 27 Apr 2026',
    tags: ['KPK Route', '12% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'lhe_mux_1',
    img: _flightCardImg,
    from: cityList[1],
    to: cityList[6],
    plane: planeList[0],
    price: 8500,
    discount: 10,
    label: '10% OFF',
    date: '01 - 03 May 2026',
    tags: ['Punjab Route', '10% OFF'],
  ),
  FlightPackage(
    id: 'lhe_qta_1',
    img: _flightCardImg,
    from: cityList[1],
    to: cityList[5],
    plane: planeList[0],
    price: 12500,
    discount: 20,
    label: '20% OFF',
    date: '05 - 07 May 2026',
    tags: ['Long Haul', '20% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'lhe_lyp_1',
    img: _flightCardImg,
    from: cityList[1],
    to: cityList[7],
    plane: planeList[2],
    price: 5500,
    discount: 8,
    label: '8% OFF',
    date: '10 - 12 May 2026',
    tags: ['Short Hop', '8% OFF'],
  ),
  FlightPackage(
    id: 'lhe_skt_1',
    img: _flightCardImg,
    from: cityList[1],
    to: cityList[12],
    plane: planeList[1],
    price: 6500,
    discount: 10,
    label: '10% OFF',
    date: '15 - 17 May 2026',
    tags: ['AirSial Hub', '10% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'lhe_gil_1',
    img: _flightCardImg,
    from: cityList[1],
    to: cityList[16],
    plane: planeList[2],
    price: 13500,
    discount: 5,
    label: '5% OFF',
    date: '20 - 22 May 2026',
    tags: ['Northern Areas', '5% OFF'],
  ),

  // ── ISLAMABAD (ISB) ─ 5 packages (ISB airport serves RWP too) ────────────
  FlightPackage(
    id: 'isb_khi_1',
    img: _flightCardImg,
    from: cityList[2],
    to: cityList[0],
    plane: planeList[3],
    price: 16200,
    discount: 15,
    label: '15% OFF',
    date: '15 - 17 Apr 2026',
    tags: ['Trunk Route', '15% OFF'],
  ),
  FlightPackage(
    id: 'isb_lhe_1',
    img: _flightCardImg,
    from: cityList[2],
    to: cityList[1],
    plane: planeList[1],
    price: 7200,
    discount: 10,
    label: '10% OFF',
    date: '20 - 22 Apr 2026',
    tags: ['Short Route', '10% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'isb_pew_1',
    img: _flightCardImg,
    from: cityList[2],
    to: cityList[4],
    plane: planeList[0],
    price: 7800,
    discount: 12,
    label: '12% OFF',
    date: '25 - 27 Apr 2026',
    tags: ['KPK Route', '12% OFF'],
  ),
  FlightPackage(
    id: 'isb_mux_1',
    img: _flightCardImg,
    from: cityList[2],
    to: cityList[6],
    plane: planeList[1],
    price: 10500,
    discount: 10,
    label: '10% OFF',
    date: '01 - 03 May 2026',
    tags: ['Punjab Route', '10% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'isb_gil_1',
    img: _flightCardImg,
    from: cityList[2],
    to: cityList[16],
    plane: planeList[2],
    price: 11500,
    discount: 8,
    label: '8% OFF',
    date: '05 - 07 May 2026',
    tags: ['Northern Areas', '8% OFF'],
  ),

  // ── PESHAWAR (PEW) ─ 5 packages ─────────────────────────────────────────
  FlightPackage(
    id: 'pew_khi_1',
    img: _flightCardImg,
    from: cityList[4],
    to: cityList[0],
    plane: planeList[0],
    price: 18200,
    discount: 20,
    label: '20% OFF',
    date: '15 - 17 Apr 2026',
    tags: ['KPK to South', '20% OFF'],
  ),
  FlightPackage(
    id: 'pew_lhe_1',
    img: _flightCardImg,
    from: cityList[4],
    to: cityList[1],
    plane: planeList[1],
    price: 9500,
    discount: 15,
    label: '15% OFF',
    date: '20 - 22 Apr 2026',
    tags: ['Popular Route', '15% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'pew_isb_1',
    img: _flightCardImg,
    from: cityList[4],
    to: cityList[2],
    plane: planeList[0],
    price: 8200,
    discount: 10,
    label: '10% OFF',
    date: '25 - 27 Apr 2026',
    tags: ['Capital Route', '10% OFF'],
  ),
  FlightPackage(
    id: 'pew_mux_1',
    img: _flightCardImg,
    from: cityList[4],
    to: cityList[6],
    plane: planeList[1],
    price: 9800,
    discount: 12,
    label: '12% OFF',
    date: '01 - 03 May 2026',
    tags: ['Punjab Route', '12% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'pew_qta_1',
    img: _flightCardImg,
    from: cityList[4],
    to: cityList[5],
    plane: planeList[2],
    price: 11200,
    discount: 10,
    label: '10% OFF',
    date: '05 - 07 May 2026',
    tags: ['Balochi Route', '10% OFF'],
  ),

  // ── MULTAN (MUX) ─ 3 packages ────────────────────────────────────────────
  FlightPackage(
    id: 'mux_khi_1',
    img: _flightCardImg,
    from: cityList[6],
    to: cityList[0],
    plane: planeList[1],
    price: 11500,
    discount: 15,
    label: '15% OFF',
    date: '15 - 17 Apr 2026',
    tags: ['Sindh Route', '15% OFF'],
  ),
  FlightPackage(
    id: 'mux_lhe_1',
    img: _flightCardImg,
    from: cityList[6],
    to: cityList[1],
    plane: planeList[0],
    price: 8500,
    discount: 10,
    label: '10% OFF',
    date: '20 - 22 Apr 2026',
    tags: ['Punjab Route', '10% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'mux_isb_1',
    img: _flightCardImg,
    from: cityList[6],
    to: cityList[2],
    plane: planeList[1],
    price: 10200,
    discount: 12,
    label: '12% OFF',
    date: '25 - 27 Apr 2026',
    tags: ['Capital Route', '12% OFF'],
  ),

  // ── FAISALABAD (LYP) ─ 3 packages ───────────────────────────────────────
  FlightPackage(
    id: 'lyp_khi_1',
    img: _flightCardImg,
    from: cityList[7],
    to: cityList[0],
    plane: planeList[0],
    price: 13500,
    discount: 15,
    label: '15% OFF',
    date: '15 - 17 Apr 2026',
    tags: ['Sindh Route', '15% OFF'],
  ),
  FlightPackage(
    id: 'lyp_lhe_1',
    img: _flightCardImg,
    from: cityList[7],
    to: cityList[1],
    plane: planeList[2],
    price: 5800,
    discount: 8,
    label: '8% OFF',
    date: '20 - 22 Apr 2026',
    tags: ['Short Hop', '8% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'lyp_isb_1',
    img: _flightCardImg,
    from: cityList[7],
    to: cityList[2],
    plane: planeList[1],
    price: 9200,
    discount: 10,
    label: '10% OFF',
    date: '25 - 27 Apr 2026',
    tags: ['Capital Route', '10% OFF'],
  ),

  // ── QUETTA (QTA) ─ 3 packages ────────────────────────────────────────────
  FlightPackage(
    id: 'qta_khi_1',
    img: _flightCardImg,
    from: cityList[5],
    to: cityList[0],
    plane: planeList[2],
    price: 9800,
    discount: 10,
    label: '10% OFF',
    date: '15 - 17 Apr 2026',
    tags: ['Balochi Route', '10% OFF'],
  ),
  FlightPackage(
    id: 'qta_lhe_1',
    img: _flightCardImg,
    from: cityList[5],
    to: cityList[1],
    plane: planeList[0],
    price: 13200,
    discount: 15,
    label: '15% OFF',
    date: '20 - 22 Apr 2026',
    tags: ['Long Haul', '15% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'qta_isb_1',
    img: _flightCardImg,
    from: cityList[5],
    to: cityList[2],
    plane: planeList[1],
    price: 11500,
    discount: 12,
    label: '12% OFF',
    date: '25 - 27 Apr 2026',
    tags: ['Capital Route', '12% OFF'],
  ),

  // ── SIALKOT (SKT) ─ 3 packages (AirSial home airport) ───────────────────
  FlightPackage(
    id: 'skt_khi_1',
    img: _flightCardImg,
    from: cityList[12],
    to: cityList[0],
    plane: planeList[1],
    price: 16200,
    discount: 12,
    label: '12% OFF',
    date: '15 - 17 Apr 2026',
    tags: ['Sindh Route', '12% OFF'],
  ),
  FlightPackage(
    id: 'skt_lhe_1',
    img: _flightCardImg,
    from: cityList[12],
    to: cityList[1],
    plane: planeList[2],
    price: 6800,
    discount: 8,
    label: '8% OFF',
    date: '20 - 22 Apr 2026',
    tags: ['Short Hop', '8% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'skt_isb_1',
    img: _flightCardImg,
    from: cityList[12],
    to: cityList[2],
    plane: planeList[0],
    price: 10800,
    discount: 10,
    label: '10% OFF',
    date: '25 - 27 Apr 2026',
    tags: ['Capital Route', '10% OFF'],
  ),

  // ── GWADAR (GWD) ─ 3 packages (PIA ATR-72 CPEC route) ───────────────────
  FlightPackage(
    id: 'gwd_khi_1',
    img: _flightCardImg,
    from: cityList[15],
    to: cityList[0],
    plane: planeList[2],
    price: 7800,
    discount: 5,
    label: '5% OFF',
    date: '15 - 17 Apr 2026',
    tags: ['CPEC City', '5% OFF'],
  ),
  FlightPackage(
    id: 'gwd_isb_1',
    img: _flightCardImg,
    from: cityList[15],
    to: cityList[2],
    plane: planeList[2],
    price: 14200,
    discount: 8,
    label: '8% OFF',
    date: '20 - 22 Apr 2026',
    tags: ['Capital Route', '8% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'gwd_lhe_1',
    img: _flightCardImg,
    from: cityList[15],
    to: cityList[1],
    plane: planeList[1],
    price: 16500,
    discount: 10,
    label: '10% OFF',
    date: '25 - 27 Apr 2026',
    tags: ['Punjab Route', '10% OFF'],
  ),

  // ── GILGIT (GIL) ─ 3 packages (PIA ATR-72 PCAA mountain route) ──────────
  FlightPackage(
    id: 'gil_isb_1',
    img: _flightCardImg,
    from: cityList[16],
    to: cityList[2],
    plane: planeList[2],
    price: 11000,
    discount: 5,
    label: '5% OFF',
    date: '15 - 17 Apr 2026',
    tags: ['Northern Areas', '5% OFF'],
  ),
  FlightPackage(
    id: 'gil_lhe_1',
    img: _flightCardImg,
    from: cityList[16],
    to: cityList[1],
    plane: planeList[2],
    price: 14200,
    discount: 8,
    label: '8% OFF',
    date: '20 - 22 Apr 2026',
    tags: ['Punjab Route', '8% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'gil_khi_1',
    img: _flightCardImg,
    from: cityList[16],
    to: cityList[0],
    plane: planeList[2],
    price: 18500,
    discount: 5,
    label: '5% OFF',
    date: '25 - 27 Apr 2026',
    tags: ['South Pakistan', '5% OFF'],
  ),

  // ── SKARDU (SKD) ─ 3 packages (seasonal PIA route) ──────────────────────
  FlightPackage(
    id: 'skd_isb_1',
    img: _flightCardImg,
    from: cityList[17],
    to: cityList[2],
    plane: planeList[2],
    price: 11500,
    discount: 5,
    label: '5% OFF',
    date: '15 - 17 Apr 2026',
    tags: ['Northern Areas', '5% OFF'],
  ),
  FlightPackage(
    id: 'skd_lhe_1',
    img: _flightCardImg,
    from: cityList[17],
    to: cityList[1],
    plane: planeList[2],
    price: 15200,
    discount: 8,
    label: '8% OFF',
    date: '20 - 22 Apr 2026',
    tags: ['Punjab Route', '8% OFF'],
    roundTrip: false,
  ),
  FlightPackage(
    id: 'skd_khi_1',
    img: _flightCardImg,
    from: cityList[17],
    to: cityList[0],
    plane: planeList[2],
    price: 19500,
    discount: 5,
    label: '5% OFF',
    date: '25 - 27 Apr 2026',
    tags: ['South Pakistan', '5% OFF'],
  ),
];
