import 'room_type.dart';

class Hotel {
  final String id;
  final String name;
  final String address;
  final String city;
  final double rating;
  final int totalReviews;
  final List<String> images;
  final List<String> amenities;
  final double pricePerNight; // Starting from price
  final String category; // '3-Star', '4-Star', '5-Star', 'Budget'
  final bool isRefundable;
  final bool hasBreakfast;
  final bool hasFreeWifi;
  final bool hasParking;
  final bool hasPool;
  final String description;
  final double distanceFromCenter; // in km
  final List<RoomType>? rooms; // Available room types
  final String? checkInTime;
  final String? checkOutTime;
  final List<String>? highlights;
  final String? neighborhood;

  Hotel({
    required this.id,
    required this.name,
    required this.address,
    required this.city,
    required this.rating,
    required this.totalReviews,
    required this.images,
    required this.amenities,
    required this.pricePerNight,
    required this.category,
    required this.isRefundable,
    required this.hasBreakfast,
    required this.hasFreeWifi,
    required this.hasParking,
    required this.hasPool,
    required this.description,
    required this.distanceFromCenter,
    this.rooms,
    this.checkInTime,
    this.checkOutTime,
    this.highlights,
    this.neighborhood,
  });
}

// Dummy data for Pakistan hotels
class PakistanHotels {
  static List<Hotel> getHotels(String city) {
    final allHotels = _getAllHotels();
    if (city.isEmpty) return allHotels;
    return allHotels.where((hotel) => hotel.city == city).toList();
  }

  static List<String> getCities() {
    return [
      'Karachi',
      'Lahore',
      'Islamabad',
      'Rawalpindi',
      'Peshawar',
      'Quetta',
      'Multan',
      'Faisalabad',
    ];
  }

  static List<Hotel> _getAllHotels() {
    return [
      // Karachi Hotels
      Hotel(
        id: '1',
        name: 'Pearl Continental Hotel Karachi',
        address: 'Club Road, Karachi',
        city: 'Karachi',
        rating: 4.5,
        totalReviews: 2850,
        images: [
          'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
          'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        ],
        amenities: [
          'Free WiFi',
          'Pool',
          'Gym',
          'Restaurant',
          'Room Service',
          'Spa'
        ],
        pricePerNight: 18500,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description:
            'Luxury 5-star hotel in the heart of Karachi with world-class amenities and excellent service.',
        distanceFromCenter: 2.5,
      ),
      Hotel(
        id: '2',
        name: 'Avari Towers Karachi',
        address: 'Fatima Jinnah Road, Karachi',
        city: 'Karachi',
        rating: 4.3,
        totalReviews: 2100,
        images: [
          'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Parking', 'Bar'],
        pricePerNight: 15000,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description:
            'Premier 5-star hotel offering stunning views and exceptional hospitality.',
        distanceFromCenter: 3.0,
      ),
      Hotel(
        id: '3',
        name: 'Hotel Mehran Karachi',
        address: 'Shahrah-e-Faisal, Karachi',
        city: 'Karachi',
        rating: 4.0,
        totalReviews: 1500,
        images: [
          'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking', 'Gym'],
        pricePerNight: 8500,
        category: '4-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description:
            'Comfortable 4-star hotel near the airport with modern facilities.',
        distanceFromCenter: 5.0,
      ),

      // Lahore Hotels
      Hotel(
        id: '4',
        name: 'Pearl Continental Hotel Lahore',
        address: 'Shahrah-e-Quaid-e-Azam, Lahore',
        city: 'Lahore',
        rating: 4.6,
        totalReviews: 3200,
        images: [
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
        ],
        amenities: [
          'Free WiFi',
          'Pool',
          'Spa',
          'Gym',
          'Restaurant',
          'Conference Rooms'
        ],
        pricePerNight: 19500,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description:
            'Lahore\'s premier 5-star hotel with excellent location and world-class service.',
        distanceFromCenter: 1.5,
      ),
      Hotel(
        id: '5',
        name: 'Avari Hotel Lahore',
        address: 'Shahrah-e-Quaid-e-Azam, Lahore',
        city: 'Lahore',
        rating: 4.4,
        totalReviews: 2400,
        images: [
          'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym', 'Spa'],
        pricePerNight: 16000,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Elegant 5-star hotel offering luxury and comfort.',
        distanceFromCenter: 2.0,
      ),
      Hotel(
        id: '6',
        name: 'Faletti\'s Hotel Lahore',
        address: 'Egerton Road, Lahore',
        city: 'Lahore',
        rating: 4.1,
        totalReviews: 1800,
        images: [
          'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking', 'Room Service'],
        pricePerNight: 9500,
        category: '4-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description:
            'Historic 4-star hotel with colonial charm and modern amenities.',
        distanceFromCenter: 1.0,
      ),

      // Islamabad Hotels
      Hotel(
        id: '7',
        name: 'Serena Hotel Islamabad',
        address: 'Khayaban-e-Suhrawardy, Islamabad',
        city: 'Islamabad',
        rating: 4.7,
        totalReviews: 2900,
        images: [
          'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800',
        ],
        amenities: [
          'Free WiFi',
          'Pool',
          'Spa',
          'Gym',
          'Restaurant',
          'Tennis Court'
        ],
        pricePerNight: 22000,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description:
            'Islamabad\'s finest 5-star hotel nestled in the Margalla Hills with breathtaking views.',
        distanceFromCenter: 3.5,
      ),
      Hotel(
        id: '8',
        name: 'Islamabad Marriott Hotel',
        address: 'Aga Khan Road, Islamabad',
        city: 'Islamabad',
        rating: 4.5,
        totalReviews: 2600,
        images: [
          'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800',
        ],
        amenities: [
          'Free WiFi',
          'Pool',
          'Gym',
          'Restaurant',
          'Bar',
          'Conference Rooms'
        ],
        pricePerNight: 20000,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description:
            'International 5-star hotel with modern facilities and excellent service.',
        distanceFromCenter: 2.5,
      ),
      Hotel(
        id: '9',
        name: 'Hotel Margala Islamabad',
        address: 'Jinnah Avenue, Islamabad',
        city: 'Islamabad',
        rating: 3.9,
        totalReviews: 1200,
        images: [
          'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking', 'Room Service'],
        pricePerNight: 7500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Comfortable 3-star hotel with good value for money.',
        distanceFromCenter: 4.0,
      ),

      // Rawalpindi Hotels
      Hotel(
        id: '10',
        name: 'Pearl Continental Rawalpindi',
        address: 'The Mall, Rawalpindi',
        city: 'Rawalpindi',
        rating: 4.3,
        totalReviews: 1900,
        images: [
          'https://images.unsplash.com/photo-1455587734955-081b22074882?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym', 'Spa'],
        pricePerNight: 16500,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: '5-star hotel offering luxury and comfort in Rawalpindi.',
        distanceFromCenter: 1.5,
      ),

      // Peshawar Hotels
      Hotel(
        id: '11',
        name: 'Pearl Continental Peshawar',
        address: 'Khyber Road, Peshawar',
        city: 'Peshawar',
        rating: 4.2,
        totalReviews: 1600,
        images: [
          'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym', 'Parking'],
        pricePerNight: 15000,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Premium 5-star hotel in Peshawar with modern amenities.',
        distanceFromCenter: 2.0,
      ),

      // Multan Hotels
      Hotel(
        id: '12',
        name: 'Ramada by Wyndham Multan',
        address: 'Abdali Road, Multan',
        city: 'Multan',
        rating: 4.1,
        totalReviews: 1400,
        images: [
          'https://images.unsplash.com/photo-1561501878-aabd62634533?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym', 'Parking'],
        pricePerNight: 12000,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Modern 4-star hotel with excellent facilities.',
        distanceFromCenter: 3.0,
      ),

      // Faisalabad Hotels
      Hotel(
        id: '13',
        name: 'Serena Hotel Faisalabad',
        address: 'Club Road, Faisalabad',
        city: 'Faisalabad',
        rating: 4.0,
        totalReviews: 1100,
        images: [
          'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Gym', 'Parking'],
        pricePerNight: 9000,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Quality 4-star hotel in the heart of Faisalabad.',
        distanceFromCenter: 2.5,
      ),

      // Additional Karachi Hotels
      Hotel(
        id: '14',
        name: 'Movenpick Hotel Karachi',
        address: 'Club Road, Karachi',
        city: 'Karachi',
        rating: 4.4,
        totalReviews: 1950,
        images: [
          'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym'],
        pricePerNight: 17000,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Luxury 5-star hotel with Swiss hospitality standards.',
        distanceFromCenter: 2.8,
      ),
      Hotel(
        id: '15',
        name: 'Ramada Plaza Karachi',
        address: 'Clifton Block 5, Karachi',
        city: 'Karachi',
        rating: 4.0,
        totalReviews: 1650,
        images: [
          'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Parking'],
        pricePerNight: 13500,
        category: '4-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Modern hotel near Clifton Beach with sea view rooms.',
        distanceFromCenter: 4.5,
      ),
      Hotel(
        id: '16',
        name: 'Beach Luxury Hotel Karachi',
        address: 'Sea View, Karachi',
        city: 'Karachi',
        rating: 4.2,
        totalReviews: 1850,
        images: [
          'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Beach Access', 'Restaurant', 'Spa'],
        pricePerNight: 16500,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Beachfront luxury hotel with stunning sea views.',
        distanceFromCenter: 6.0,
      ),
      Hotel(
        id: '17',
        name: 'Hotel One Karachi',
        address: 'Gulshan-e-Iqbal, Karachi',
        city: 'Karachi',
        rating: 3.8,
        totalReviews: 1200,
        images: [
          'https://images.unsplash.com/photo-1564769610726-6649e8efb2e7?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 6500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Budget-friendly 3-star hotel with clean rooms.',
        distanceFromCenter: 8.0,
      ),
      Hotel(
        id: '18',
        name: 'Sheraton Karachi Hotel',
        address: 'Club Road, Karachi',
        city: 'Karachi',
        rating: 4.5,
        totalReviews: 2250,
        images: [
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Spa', 'Gym', 'Restaurant', 'Bar'],
        pricePerNight: 19500,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'International luxury hotel with world-class amenities.',
        distanceFromCenter: 2.2,
      ),

      // Additional Lahore Hotels
      Hotel(
        id: '19',
        name: 'Nishat Hotel Lahore',
        address: 'Mall Road, Lahore',
        city: 'Lahore',
        rating: 3.9,
        totalReviews: 1450,
        images: [
          'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking', 'Room Service'],
        pricePerNight: 8500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Centrally located 3-star hotel on historic Mall Road.',
        distanceFromCenter: 0.8,
      ),
      Hotel(
        id: '20',
        name: 'Luxus Grand Hotel Lahore',
        address: 'Gulberg, Lahore',
        city: 'Lahore',
        rating: 4.3,
        totalReviews: 1780,
        images: [
          'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym', 'Spa'],
        pricePerNight: 14500,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Upscale 4-star hotel in trendy Gulberg area.',
        distanceFromCenter: 3.5,
      ),
      Hotel(
        id: '21',
        name: 'Hotel One Lahore',
        address: 'Ferozepur Road, Lahore',
        city: 'Lahore',
        rating: 3.7,
        totalReviews: 1100,
        images: [
          'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 5500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Affordable hotel with good value for money.',
        distanceFromCenter: 5.5,
      ),
      Hotel(
        id: '22',
        name: 'Royal Swiss Lahore',
        address: 'DHA Phase 5, Lahore',
        city: 'Lahore',
        rating: 4.2,
        totalReviews: 1620,
        images: [
          'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'],
        pricePerNight: 12500,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Boutique hotel in upscale DHA neighborhood.',
        distanceFromCenter: 6.0,
      ),
      Hotel(
        id: '23',
        name: 'Best Western Premier Lahore',
        address: 'Jail Road, Lahore',
        city: 'Lahore',
        rating: 4.1,
        totalReviews: 1520,
        images: [
          'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym', 'Parking'],
        pricePerNight: 11500,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Modern hotel with international standards.',
        distanceFromCenter: 4.0,
      ),
      Hotel(
        id: '24',
        name: 'Hospitality Inn Lahore',
        address: 'Township, Lahore',
        city: 'Lahore',
        rating: 3.6,
        totalReviews: 950,
        images: [
          'https://images.unsplash.com/photo-1561501878-aabd62634533?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 4500,
        category: 'Budget',
        isRefundable: false,
        hasBreakfast: false,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Simple and clean budget hotel.',
        distanceFromCenter: 7.5,
      ),

      // Additional Islamabad Hotels
      Hotel(
        id: '25',
        name: 'Ramada Islamabad',
        address: 'Blue Area, Islamabad',
        city: 'Islamabad',
        rating: 4.2,
        totalReviews: 1680,
        images: [
          'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'],
        pricePerNight: 13500,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Business hotel in the heart of Islamabad.',
        distanceFromCenter: 1.0,
      ),
      Hotel(
        id: '26',
        name: 'Best Western Islamabad',
        address: 'F-7 Markaz, Islamabad',
        city: 'Islamabad',
        rating: 4.0,
        totalReviews: 1420,
        images: [
          'https://images.unsplash.com/photo-1455587734955-081b22074882?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Gym', 'Parking'],
        pricePerNight: 10500,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Comfortable hotel near F-7 shopping area.',
        distanceFromCenter: 2.5,
      ),
      Hotel(
        id: '27',
        name: 'Pearl Continental Bhurban',
        address: 'Bhurban, Near Islamabad',
        city: 'Islamabad',
        rating: 4.6,
        totalReviews: 2100,
        images: [
          'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Spa', 'Gym', 'Restaurant', 'Golf'],
        pricePerNight: 25000,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Luxury resort hotel in the scenic Murree hills.',
        distanceFromCenter: 50.0,
      ),
      Hotel(
        id: '28',
        name: 'Envoy Continental Islamabad',
        address: 'Fazal-ul-Haq Road, Islamabad',
        city: 'Islamabad',
        rating: 3.9,
        totalReviews: 1250,
        images: [
          'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 8000,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Good value 3-star hotel for business travelers.',
        distanceFromCenter: 3.0,
      ),
      Hotel(
        id: '29',
        name: 'Roomy Luxury Hotel Islamabad',
        address: 'G-9 Markaz, Islamabad',
        city: 'Islamabad',
        rating: 3.8,
        totalReviews: 1050,
        images: [
          'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 7000,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Spacious rooms at affordable prices.',
        distanceFromCenter: 4.5,
      ),

      // Additional Rawalpindi Hotels
      Hotel(
        id: '30',
        name: 'Regalia Hotel Rawalpindi',
        address: 'Murree Road, Rawalpindi',
        city: 'Rawalpindi',
        rating: 3.7,
        totalReviews: 980,
        images: [
          'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 6000,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Convenient hotel on main Murree Road.',
        distanceFromCenter: 2.5,
      ),
      Hotel(
        id: '31',
        name: 'Luxury Suites Rawalpindi',
        address: 'Saddar, Rawalpindi',
        city: 'Rawalpindi',
        rating: 3.9,
        totalReviews: 1150,
        images: [
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking', 'Room Service'],
        pricePerNight: 7500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Comfortable suites in bustling Saddar area.',
        distanceFromCenter: 1.0,
      ),
      Hotel(
        id: '32',
        name: 'Shalimar Hotel Rawalpindi',
        address: 'Committee Chowk, Rawalpindi',
        city: 'Rawalpindi',
        rating: 4.0,
        totalReviews: 1320,
        images: [
          'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking', 'Gym'],
        pricePerNight: 9500,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Business hotel in commercial district.',
        distanceFromCenter: 1.5,
      ),

      // Additional Peshawar Hotels
      Hotel(
        id: '33',
        name: 'Shelton Rezidor Peshawar',
        address: 'University Road, Peshawar',
        city: 'Peshawar',
        rating: 4.0,
        totalReviews: 1380,
        images: [
          'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'],
        pricePerNight: 11000,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Modern hotel with international standards.',
        distanceFromCenter: 3.5,
      ),
      Hotel(
        id: '34',
        name: 'Hotel One Peshawar',
        address: 'GT Road, Peshawar',
        city: 'Peshawar',
        rating: 3.7,
        totalReviews: 920,
        images: [
          'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 5500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Budget hotel with clean rooms.',
        distanceFromCenter: 5.0,
      ),
      Hotel(
        id: '35',
        name: 'Frontier Hotel Peshawar',
        address: 'Saddar Road, Peshawar',
        city: 'Peshawar',
        rating: 3.8,
        totalReviews: 1050,
        images: [
          'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 6500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Traditional hospitality in the heart of Peshawar.',
        distanceFromCenter: 2.0,
      ),

      // Additional Quetta Hotels
      Hotel(
        id: '36',
        name: 'Serena Hotel Quetta',
        address: 'Shahrah-e-Zarghoon, Quetta',
        city: 'Quetta',
        rating: 4.3,
        totalReviews: 1450,
        images: [
          'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Gym', 'Parking', 'Spa'],
        pricePerNight: 14000,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Premier hotel in Quetta with excellent service.',
        distanceFromCenter: 2.5,
      ),
      Hotel(
        id: '37',
        name: 'Lourdes Hotel Quetta',
        address: 'Jinnah Road, Quetta',
        city: 'Quetta',
        rating: 3.9,
        totalReviews: 880,
        images: [
          'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 7500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Comfortable stay in central Quetta.',
        distanceFromCenter: 1.5,
      ),
      Hotel(
        id: '38',
        name: 'New Lourdes Hotel Quetta',
        address: 'Mall Road, Quetta',
        city: 'Quetta',
        rating: 3.7,
        totalReviews: 750,
        images: [
          'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 6000,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Good value hotel with mountain views.',
        distanceFromCenter: 2.0,
      ),

      // Additional Multan Hotels
      Hotel(
        id: '39',
        name: 'Hotel One Multan',
        address: 'Abdali Road, Multan',
        city: 'Multan',
        rating: 3.8,
        totalReviews: 1020,
        images: [
          'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 5500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Affordable accommodation in Multan.',
        distanceFromCenter: 3.5,
      ),
      Hotel(
        id: '40',
        name: 'Chenab Club Hotel Multan',
        address: 'Jail Road, Multan',
        city: 'Multan',
        rating: 4.0,
        totalReviews: 1180,
        images: [
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym', 'Parking'],
        pricePerNight: 10500,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Premium hotel with recreational facilities.',
        distanceFromCenter: 4.0,
      ),
      Hotel(
        id: '41',
        name: 'Sindbad Hotel Multan',
        address: 'Bosan Road, Multan',
        city: 'Multan',
        rating: 3.6,
        totalReviews: 850,
        images: [
          'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 5000,
        category: 'Budget',
        isRefundable: false,
        hasBreakfast: false,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Simple and economical hotel.',
        distanceFromCenter: 5.5,
      ),

      // Additional Faisalabad Hotels
      Hotel(
        id: '42',
        name: 'Hotel One Faisalabad',
        address: 'Peoples Colony, Faisalabad',
        city: 'Faisalabad',
        rating: 3.7,
        totalReviews: 980,
        images: [
          'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 4500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Clean budget hotel in textile city.',
        distanceFromCenter: 4.0,
      ),
      Hotel(
        id: '43',
        name: 'Luxury Hotel Faisalabad',
        address: 'Susan Road, Faisalabad',
        city: 'Faisalabad',
        rating: 3.9,
        totalReviews: 1150,
        images: [
          'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Gym', 'Parking'],
        pricePerNight: 7500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Mid-range hotel with modern amenities.',
        distanceFromCenter: 3.0,
      ),
      Hotel(
        id: '44',
        name: 'Regency Plaza Faisalabad',
        address: 'Kohinoor City, Faisalabad',
        city: 'Faisalabad',
        rating: 4.1,
        totalReviews: 1280,
        images: [
          'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym', 'Parking'],
        pricePerNight: 11000,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Upscale hotel with full facilities.',
        distanceFromCenter: 2.5,
      ),

      // Premium Karachi Hotels (Additional)
      Hotel(
        id: '45',
        name: 'Regent Plaza Hotel Karachi',
        address: 'Shahrah-e-Faisal, Karachi',
        city: 'Karachi',
        rating: 4.1,
        totalReviews: 1780,
        images: [
          'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym', 'Spa'],
        pricePerNight: 14500,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Business hotel near Karachi Airport.',
        distanceFromCenter: 8.0,
      ),
      Hotel(
        id: '46',
        name: 'Marriott Hotel Karachi',
        address: 'Abdullah Haroon Road, Karachi',
        city: 'Karachi',
        rating: 4.6,
        totalReviews: 2450,
        images: [
          'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        ],
        amenities: [
          'FreekWiFi',
          'Pool',
          'Spa',
          'Gym',
          'Restaurant',
          'Bar',
          'Conference Rooms'
        ],
        pricePerNight: 21000,
        category: '5-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'International luxury brand with premium service.',
        distanceFromCenter: 3.5,
      ),
      Hotel(
        id: '47',
        name: 'Oyster Bay Karachi',
        address: 'DHA Phase 8, Karachi',
        city: 'Karachi',
        rating: 4.0,
        totalReviews: 1520,
        images: [
          'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking', 'Room Service'],
        pricePerNight: 10500,
        category: '4-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Boutique hotel in upscale DHA neighborhood.',
        distanceFromCenter: 12.0,
      ),

      // Premium Lahore Hotels (Additional)
      Hotel(
        id: '48',
        name: 'Nishat Hotel Emporium Mall',
        address: 'Abdul Haque Road, Lahore',
        city: 'Lahore',
        rating: 4.2,
        totalReviews: 1680,
        images: [
          'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
        ],
        amenities: [
          'Free WiFi',
          'Pool',
          'Restaurant',
          'Gym',
          'Shopping Access'
        ],
        pricePerNight: 13000,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Modern hotel connected to Pakistan\'s largest mall.',
        distanceFromCenter: 7.0,
      ),
      Hotel(
        id: '49',
        name: 'The Residency Hotel Lahore',
        address: 'Main Boulevard, Lahore',
        city: 'Lahore',
        rating: 3.8,
        totalReviews: 1250,
        images: [
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 7000,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Value hotel on Main Boulevard Gulberg.',
        distanceFromCenter: 4.5,
      ),
      Hotel(
        id: '50',
        name: 'Grand Plaza Hotel Lahore',
        address: 'MM Alam Road, Lahore',
        city: 'Lahore',
        rating: 4.0,
        totalReviews: 1450,
        images: [
          'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
        ],
        amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Parking'],
        pricePerNight: 10000,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: true,
        description: 'Stylish hotel on famous food street.',
        distanceFromCenter: 3.8,
      ),

      // Boutique & Business Hotels
      Hotel(
        id: '51',
        name: 'Cube Boutique Hotel Karachi',
        address: 'Clifton Block 4, Karachi',
        city: 'Karachi',
        rating: 4.3,
        totalReviews: 890,
        images: [
          'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking', 'Rooftop'],
        pricePerNight: 12500,
        category: '4-Star',
        isRefundable: true,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Trendy boutique hotel with modern design.',
        distanceFromCenter: 5.5,
      ),
      Hotel(
        id: '52',
        name: 'Carlton Hotel Lahore',
        address: 'Shahrah-e-Quaid-e-Azam, Lahore',
        city: 'Lahore',
        rating: 3.9,
        totalReviews: 1120,
        images: [
          'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking', 'Business Center'],
        pricePerNight: 8500,
        category: '3-Star',
        isRefundable: false,
        hasBreakfast: true,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Business hotel in commercial area.',
        distanceFromCenter: 2.5,
      ),
      Hotel(
        id: '53',
        name: 'Express Inn Islamabad',
        address: 'I-8 Markaz, Islamabad',
        city: 'Islamabad',
        rating: 3.6,
        totalReviews: 780,
        images: [
          'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800',
        ],
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        pricePerNight: 5500,
        category: 'Budget',
        isRefundable: false,
        hasBreakfast: false,
        hasFreeWifi: true,
        hasParking: true,
        hasPool: false,
        description: 'Quick stay budget hotel.',
        distanceFromCenter: 6.0,
      ),
    ];
  }

  static List<Hotel> searchHotels({
    required String city,
    String? category,
    double? maxPrice,
    double? minRating,
    bool? hasPool,
    bool? hasBreakfast,
  }) {
    var hotels = getHotels(city);

    if (category != null && category.isNotEmpty) {
      hotels = hotels.where((h) => h.category == category).toList();
    }

    if (maxPrice != null) {
      hotels = hotels.where((h) => h.pricePerNight <= maxPrice).toList();
    }

    if (minRating != null) {
      hotels = hotels.where((h) => h.rating >= minRating).toList();
    }

    if (hasPool == true) {
      hotels = hotels.where((h) => h.hasPool).toList();
    }

    if (hasBreakfast == true) {
      hotels = hotels.where((h) => h.hasBreakfast).toList();
    }

    // Sort by rating (highest first)
    hotels.sort((a, b) => b.rating.compareTo(a.rating));

    return hotels;
  }
}
