class RailwayStation {
  final String name;
  final String code;
  final String city;

  RailwayStation({
    required this.name,
    required this.code,
    required this.city,
  });
}

class PakistanRailwayStations {
  static List<RailwayStation> getAllStations() {
    return [
      RailwayStation(name: 'Ab-I-Gum', code: 'ABG', city: 'Balochistan'),
      RailwayStation(name: 'Abdul Hakim', code: 'ABH', city: 'Khanewal'),
      RailwayStation(name: 'Ajnala', code: 'AJN', city: 'Amritsar'),
      RailwayStation(
          name: 'Akhtar Karnana', code: 'AKN', city: 'Mandi Bahauddin'),
      RailwayStation(name: 'Ala', code: 'ALA', city: 'Punjab'),
      RailwayStation(name: 'Ali Pur Chtha', code: 'APC', city: 'Gujranwala'),
      RailwayStation(name: 'Alluwali', code: 'ALW', city: 'Punjab'),
      RailwayStation(name: 'Amri', code: 'AMR', city: 'Jamshoro'),
      RailwayStation(name: 'Arif Wala', code: 'ARW', city: 'Pakpattan'),
      RailwayStation(name: 'Ashanpur Ahp', code: 'ASP', city: 'Punjab'),
      RailwayStation(name: 'Attock City Jn.', code: 'ATC', city: 'Attock'),
      RailwayStation(name: 'Babarkach', code: 'BBK', city: 'Balochistan'),
      RailwayStation(name: 'Babri Banda', code: 'BBB', city: 'KPK'),
      RailwayStation(name: 'Badah', code: 'BDA', city: 'Punjab'),
      RailwayStation(name: 'Badami Bagh', code: 'BDB', city: 'Lahore'),
      RailwayStation(name: 'Baddomalhi', code: 'BDM', city: 'Narowal'),
      RailwayStation(name: 'Badal Nala', code: 'BDN', city: 'Karachi'),
      RailwayStation(name: 'Bahawalpur', code: 'BWP', city: 'Bahawalpur'),
      RailwayStation(name: 'Bakhwali', code: 'BKW', city: 'Punjab'),
      RailwayStation(name: 'Bakhtiarabad Domki', code: 'BKD', city: 'Sindh'),
      RailwayStation(name: 'Bakrani Road', code: 'BKN', city: 'Sindh'),
      RailwayStation(name: 'Baldher', code: 'BLR', city: 'Punjab'),
      RailwayStation(name: 'Bali Shah', code: 'BLS', city: 'Sindh'),
      RailwayStation(name: 'Bandhi', code: 'BND', city: 'Punjab'),
      RailwayStation(name: 'Bandwali', code: 'BDW', city: 'Karachi'),
      RailwayStation(name: 'Banhmianwala', code: 'BMW', city: 'Punjab'),
      RailwayStation(name: 'Basirpur', code: 'BSP', city: 'Okara'),
      RailwayStation(name: 'Basti Darvesh Lashari', code: 'BDL', city: 'Sindh'),
      RailwayStation(name: 'Behal', code: 'BHL', city: 'Punjab'),
      RailwayStation(name: 'Belili', code: 'BLL', city: 'Balochistan'),
      RailwayStation(name: 'Bhalike', code: 'BLK', city: 'Sheikhupura'),
      RailwayStation(name: 'Bhalwal', code: 'BHW', city: 'Sargodha'),
      RailwayStation(name: 'Bhan Sayadabad', code: 'BNS', city: 'Sindh'),
      RailwayStation(name: 'Bhakkar', code: 'BKR', city: 'Bhakkar'),
      RailwayStation(
          name: 'Bhiria Road', code: 'BHR', city: 'Naushahro Feroze'),
      RailwayStation(name: 'Bin Qasim', code: 'BNQ', city: 'Karachi'),
      RailwayStation(name: 'Bosal', code: 'BSL', city: 'Chakwal'),
      RailwayStation(name: 'Bosal Sharif', code: 'BSS', city: 'Chakwal'),
      RailwayStation(name: 'Bostan', code: 'BST', city: 'Pishin'),
      RailwayStation(name: 'Braudabad', code: 'BRD', city: 'Sindh'),
      RailwayStation(name: 'Buchiana', code: 'BCN', city: 'Faisalabad'),
      RailwayStation(name: 'Budh', code: 'BDH', city: 'Punjab'),
      RailwayStation(
          name: 'Cadet College Petaro', code: 'CCP', city: 'Jamshoro'),
      RailwayStation(name: 'Chak Jhumra', code: 'CJR', city: 'Faisalabad'),
      RailwayStation(name: 'Chak Lala', code: 'CKL', city: 'Rawalpindi'),
      RailwayStation(name: 'Chak Saida', code: 'CSD', city: 'Punjab'),
      RailwayStation(name: 'Chak Sher Muhammad', code: 'CSM', city: 'Punjab'),
      RailwayStation(name: 'Chaman', code: 'CHM', city: 'Chaman'),
      RailwayStation(name: 'Chawinda', code: 'CHD', city: 'Sialkot'),
      RailwayStation(name: 'Chenab Nagar', code: 'CBN', city: 'Chiniot'),
      RailwayStation(name: 'Chhab', code: 'CHB', city: 'KPK'),
      RailwayStation(name: 'Chichawatni', code: 'CHW', city: 'Sahiwal'),
      RailwayStation(name: 'Chichoki Malian', code: 'CKM', city: 'Sheikhupura'),
      RailwayStation(name: 'Chilianwala', code: 'CLW', city: 'Gujrat'),
      RailwayStation(name: 'Chiniot', code: 'CNT', city: 'Chiniot'),
      RailwayStation(name: 'Chura Sharif', code: 'CHS', city: 'Punjab'),
      RailwayStation(name: 'Dabehji', code: 'DBJ', city: 'Sindh'),
      RailwayStation(name: 'Dadu', code: 'DDU', city: 'Dadu'),
      RailwayStation(name: 'Daharki', code: 'DHK', city: 'Ghotki'),
      RailwayStation(name: 'Daryakhan', code: 'DYK', city: 'Bhakkar'),
      RailwayStation(name: 'Daud', code: 'DWD', city: 'Punjab'),
      RailwayStation(name: 'Daud Khel', code: 'DKL', city: 'Mianwali'),
      RailwayStation(name: 'Dera Allahyar', code: 'DAY', city: 'Jaffarabad'),
      RailwayStation(name: 'Dera Din Panah', code: 'DDP', city: 'Punjab'),
      RailwayStation(
          name: 'Dera Ghazi Khan', code: 'DGK', city: 'Dera Ghazi Khan'),
      RailwayStation(name: 'Dera Murad Jamali', code: 'DMJ', city: 'Nasirabad'),
      RailwayStation(name: 'Dera Nawab Sahib', code: 'DNS', city: 'Bahawalpur'),
      RailwayStation(name: 'Dina', code: 'DNA', city: 'Jhelum'),
      RailwayStation(name: 'Dinga', code: 'DNG', city: 'Gujrat'),
      RailwayStation(name: 'Domala', code: 'DMA', city: 'Punjab'),
      RailwayStation(name: 'Domel', code: 'DML', city: 'Punjab'),
      RailwayStation(name: 'Dorata', code: 'DRT', city: 'Punjab'),
      RailwayStation(name: 'Dour', code: 'DOR', city: 'Punjab'),
      RailwayStation(name: 'Drigh Road', code: 'DGR', city: 'Karachi'),
      RailwayStation(name: 'Dunyapur', code: 'DYP', city: 'Lodhran'),
      RailwayStation(name: 'Faisalabad', code: 'LYP', city: 'Faisalabad'),
      RailwayStation(name: 'Faqirabad', code: 'FQD', city: 'KPK'),
      RailwayStation(name: 'Farooqabad', code: 'FQB', city: 'Sheikhupura'),
      RailwayStation(name: 'Fateh Jang', code: 'FTJ', city: 'Attock'),
      RailwayStation(name: 'Fazilpur Dhandi', code: 'FPD', city: 'Rajanpur'),
      RailwayStation(name: 'Firoza', code: 'FRZ', city: 'Vehari'),
      RailwayStation(name: 'Gagoo', code: 'GGO', city: 'Vehari'),
      RailwayStation(name: 'Gambat', code: 'GMB', city: 'Khairpur'),
      RailwayStation(name: 'Gilawala', code: 'GLW', city: 'Punjab'),
      RailwayStation(name: 'Ghotki', code: 'GHT', city: 'Ghotki'),
      RailwayStation(name: 'Gojra', code: 'GJR', city: 'Toba Tek Singh'),
      RailwayStation(name: 'Golra Sharif', code: 'GLR', city: 'Islamabad'),
      RailwayStation(name: 'Gujar Khan', code: 'GJK', city: 'Rawalpindi'),
      RailwayStation(name: 'Gujranwala', code: 'GJW', city: 'Gujranwala'),
      RailwayStation(name: 'Gujrat', code: 'GJT', city: 'Gujrat'),
      RailwayStation(name: 'Gulistan', code: 'GLS', city: 'Killa Abdullah'),
      RailwayStation(name: 'Gunna Kalan', code: 'GNK', city: 'Sindh'),
      RailwayStation(name: 'Gurmani', code: 'GRM', city: 'Punjab'),
      RailwayStation(name: 'Habib Kot Jn.', code: 'HKJ', city: 'Sindh'),
      RailwayStation(name: 'Habibkot', code: 'HBK', city: 'Sindh'),
      RailwayStation(name: 'Habit Shaheed', code: 'HBS', city: 'Sindh'),
      RailwayStation(name: 'Hafizabad', code: 'HFZ', city: 'Hafizabad'),
      RailwayStation(name: 'Hariah', code: 'HRH', city: 'Punjab'),
      RailwayStation(name: 'Haranpur', code: 'HRP', city: 'Punjab'),
      RailwayStation(name: 'Haripur Hazara', code: 'HPH', city: 'Haripur'),
      RailwayStation(name: 'Hasan Abdal', code: 'HAB', city: 'Attock'),
      RailwayStation(name: 'Haveli Wasawewala', code: 'HWW', city: 'Sahiwal'),
      RailwayStation(name: 'Havelian', code: 'HVL', city: 'Abbottabad'),
      RailwayStation(name: 'Hurnai', code: 'HRN', city: 'Bolan'),
      RailwayStation(name: 'Hyderabad Jn.', code: 'HYD', city: 'Hyderabad'),
      RailwayStation(name: 'Injra', code: 'INJ', city: 'KPK'),
      RailwayStation(name: 'Jacobabad Jn.', code: 'JAC', city: 'Jacobabad'),
      RailwayStation(name: 'Jahangira Road', code: 'JGR', city: 'Nowshera'),
      RailwayStation(name: 'Jahania', code: 'JHN', city: 'Jhang'),
      RailwayStation(name: 'Jamanshah', code: 'JMS', city: 'Punjab'),
      RailwayStation(name: 'Jampur', code: 'JMR', city: 'Rajanpur'),
      RailwayStation(name: 'Jamraniwah', code: 'JRW', city: 'Punjab'),
      RailwayStation(name: 'Jand', code: 'JND', city: 'Attock'),
      RailwayStation(name: 'Jaranwala', code: 'JNW', city: 'Faisalabad'),
      RailwayStation(
          name: 'Jaura Karnana', code: 'JKN', city: 'Mandi Bahauddin'),
      RailwayStation(name: 'Jhalar', code: 'JLR', city: 'Punjab'),
      RailwayStation(name: 'Jhamat', code: 'JMT', city: 'Punjab'),
      RailwayStation(name: 'Jhangsadar', code: 'JGS', city: 'Jhang'),
      RailwayStation(name: 'Jhelum', code: 'JHL', city: 'Jhelum'),
      RailwayStation(name: 'Jhimpir', code: 'JMP', city: 'Thatta'),
      RailwayStation(name: 'Johra Abad', code: 'JOA', city: 'Khushab'),
      RailwayStation(name: 'Jungshahi', code: 'JGH', city: 'Thatta'),
      RailwayStation(name: 'Kahror Pakka', code: 'KRP', city: 'Lodhran'),
      RailwayStation(name: 'Kala Khatai', code: 'KKT', city: 'Punjab'),
      RailwayStation(name: 'Kallurkot', code: 'KLK', city: 'Bhakkar'),
      RailwayStation(name: 'Kamalia', code: 'KML', city: 'Toba Tek Singh'),
      RailwayStation(name: 'Kandhkot', code: 'KDK', city: 'Kashmore'),
      RailwayStation(name: 'Kanganpur', code: 'KGP', city: 'Sahiwal'),
      RailwayStation(name: 'Kanjwani', code: 'KJW', city: 'Faisalabad'),
      RailwayStation(name: 'Karor', code: 'KRR', city: 'Layyah'),
      RailwayStation(name: 'Karachi Cantt.', code: 'KCT', city: 'Karachi'),
      RailwayStation(name: 'Karachi City', code: 'KRC', city: 'Karachi'),
      RailwayStation(name: 'Kashmor Colony', code: 'KMC', city: 'Kashmore'),
      RailwayStation(name: 'Kasur Jn.', code: 'KSR', city: 'Kasur'),
      RailwayStation(name: 'Kahal', code: 'KHL', city: 'Attock'),
      RailwayStation(name: 'Khairpur', code: 'KHP', city: 'Khairpur'),
      RailwayStation(name: 'Khanewal Jn.', code: 'KWL', city: 'Khanewal'),
      RailwayStation(name: 'Khanpur Jn.', code: 'KNP', city: 'Rahim Yar Khan'),
      RailwayStation(name: 'Kharian Cantt.', code: 'KHC', city: 'Gujrat'),
      RailwayStation(name: 'Khatakabad', code: 'KTB', city: 'KPK'),
      RailwayStation(name: 'Khudian', code: 'KHD', city: 'Kasur'),
      RailwayStation(name: 'Khushab', code: 'KHB', city: 'Khushab'),
      RailwayStation(
          name: 'Killaabdullah', code: 'KLA', city: 'Killa Abdullah'),
      RailwayStation(name: 'Kimari', code: 'KMR', city: 'Karachi'),
      RailwayStation(name: 'Kohat Cantt.', code: 'KHT', city: 'Kohat'),
      RailwayStation(name: 'Kolpur', code: 'KPR', city: 'Bolan'),
      RailwayStation(name: 'Kot Addu Jn.', code: 'KDJ', city: 'Muzaffargarh'),
      RailwayStation(name: 'Kot Lakhpat', code: 'KLP', city: 'Lahore'),
      RailwayStation(name: 'Kot Laloo', code: 'KLL', city: 'Punjab'),
      RailwayStation(name: 'Kot Najibullah', code: 'KNJ', city: 'Punjab'),
      RailwayStation(name: 'Kot Radha Kishen', code: 'KRK', city: 'Kasur'),
      RailwayStation(name: 'Kotsultan', code: 'KST', city: 'Punjab'),
      RailwayStation(name: 'Kotri Jn.', code: 'KTR', city: 'Jamshoro'),
      RailwayStation(name: 'Kuchlak', code: 'KCK', city: 'Quetta'),
      RailwayStation(name: 'Kundian', code: 'KNI', city: 'Mianwali'),
      RailwayStation(name: 'Lahore Cantt.', code: 'LHC', city: 'Lahore'),
      RailwayStation(name: 'Lahore Jn.', code: 'LHR', city: 'Lahore'),
      RailwayStation(name: 'Lakha Road', code: 'LKD', city: 'Punjab'),
      RailwayStation(name: 'Lakha Road (Shorkot)', code: 'LKR', city: 'Jhang'),
      RailwayStation(name: 'Lakhi Shah Sadar', code: 'LSS', city: 'Sindh'),
      RailwayStation(name: 'Lala Musa Jn.', code: 'LMJ', city: 'Gujrat'),
      RailwayStation(name: 'Landhi Jn.', code: 'LND', city: 'Karachi'),
      RailwayStation(name: 'Langar', code: 'LNG', city: 'Punjab'),
      RailwayStation(name: 'Larkana Jn.', code: 'LRK', city: 'Larkana'),
      RailwayStation(name: 'Leiah', code: 'LIA', city: 'Layyah'),
      RailwayStation(name: 'Liaquatpur', code: 'LQP', city: 'Rahim Yar Khan'),
      RailwayStation(name: 'Lodhran Jn.', code: 'LDR', city: 'Lodhran'),
      RailwayStation(name: 'Mach', code: 'MCH', city: 'Bolan'),
      RailwayStation(name: 'Machhianwala', code: 'MCW', city: 'Jhang'),
      RailwayStation(name: 'Madeji Road', code: 'MDJ', city: 'Sindh'),
      RailwayStation(name: 'Mahrabpur', code: 'MRP', city: 'Naushahro Feroze'),
      RailwayStation(name: 'Mailsi', code: 'MLS', city: 'Vehari'),
      RailwayStation(name: 'Maibal', code: 'MBL', city: 'Punjab'),
      RailwayStation(
          name: 'Main Booking Office Lhr', code: 'MBO', city: 'Lahore'),
      RailwayStation(name: 'Mahmudkot', code: 'MMK', city: 'Muzaffargarh'),
      RailwayStation(name: 'Makhad Road', code: 'MKR', city: 'Attock'),
      RailwayStation(
          name: 'Malakwal Jn.', code: 'MLW', city: 'Mandi Bahauddin'),
      RailwayStation(name: 'Mamu Kanjan', code: 'MKJ', city: 'Faisalabad'),
      RailwayStation(name: 'Mandi Ahmadabad', code: 'MAB', city: 'Sheikhupura'),
      RailwayStation(
          name: 'Mandi Bahauddin', code: 'MBD', city: 'Mandi Bahauddin'),
      RailwayStation(name: 'Mandi Burewala', code: 'MBR', city: 'Vehari'),
      RailwayStation(name: 'Margala', code: 'MGL', city: 'Islamabad'),
      RailwayStation(name: 'Mari Indus', code: 'MRN', city: 'Mianwali'),
      RailwayStation(name: 'Massan', code: 'MSN', city: 'Attock'),
      RailwayStation(name: 'Metha Suja', code: 'MTS', city: 'Punjab'),
      RailwayStation(name: 'Mian Channue', code: 'MCN', city: 'Khanewal'),
      RailwayStation(name: 'Mianwali', code: 'MNW', city: 'Mianwali'),
      RailwayStation(name: 'Mirpur Khas Jn.', code: 'MPK', city: 'Mirpur Khas'),
      RailwayStation(name: 'Mirpur Mathelo', code: 'MPM', city: 'Ghotki'),
      RailwayStation(name: 'Mithan Kott', code: 'MTK', city: 'Rajjanpur'),
      RailwayStation(name: 'Mohinjo Daro', code: 'MJD', city: 'Larkana'),
      RailwayStation(name: 'Mona', code: 'MON', city: 'Punjab'),
      RailwayStation(name: 'Mubarakpur', code: 'MBP', city: 'Punjab'),
      RailwayStation(name: 'Multan Cantt.', code: 'MUX', city: 'Multan'),
      RailwayStation(name: 'Murad Chishti', code: 'MRC', city: 'Okara'),
      RailwayStation(name: 'Muzaffargarh', code: 'MZG', city: 'Muzaffargarh'),
      RailwayStation(name: 'Khost', code: 'KHO', city: 'Balochistan'),
      RailwayStation(name: 'Nakas', code: 'NKS', city: 'Balochistan'),
      RailwayStation(name: 'Namal', code: 'NML', city: 'Mianwali'),
      RailwayStation(name: 'Nankana Sb.', code: 'NNK', city: 'Nankana Sahib'),
      RailwayStation(name: 'Narang', code: 'NRG', city: 'Sheikhupura'),
      RailwayStation(name: 'Nari', code: 'NRI', city: 'Balochistan'),
      RailwayStation(name: 'Narowal Jn.', code: 'NRW', city: 'Narowal'),
      RailwayStation(
          name: 'Nawabshah Jn.', code: 'NWS', city: 'Shahid Benazirabad'),
      RailwayStation(name: 'Nowshera Jn.', code: 'NWJ', city: 'Nowshera'),
      RailwayStation(name: 'Nur Shah', code: 'NSH', city: 'Jhang'),
      RailwayStation(name: 'Okara', code: 'OKR', city: 'Okara'),
      RailwayStation(name: 'Okara Cantt.', code: 'OKC', city: 'Okara'),
      RailwayStation(name: 'Pabbi', code: 'PBB', city: 'Nowshera'),
      RailwayStation(name: 'Padidan', code: 'PDN', city: 'Naushahro Feroze'),
      RailwayStation(name: 'Pai Khel', code: 'PKL', city: 'Mianwali'),
      RailwayStation(name: 'Pakhowal', code: 'PKW', city: 'Faisalabad'),
      RailwayStation(name: 'Pakpattan', code: 'PKP', city: 'Pakpattan'),
      RailwayStation(name: 'Panjgirain', code: 'PJG', city: 'Punjab'),
      RailwayStation(name: 'Pano Akil', code: 'PAK', city: 'Sukkur'),
      RailwayStation(name: 'Pasrur', code: 'PSR', city: 'Sialkot'),
      RailwayStation(name: 'Pattoki', code: 'PTK', city: 'Kasur'),
      RailwayStation(name: 'Pejowali', code: 'PJW', city: 'Punjab'),
      RailwayStation(name: 'Peshawar Cantt.', code: 'PEC', city: 'Peshawar'),
      RailwayStation(name: 'Peshawar City', code: 'PWC', city: 'Peshawar'),
      RailwayStation(name: 'Phulji', code: 'PHJ', city: 'Sindh'),
      RailwayStation(name: 'Phularwan', code: 'PHW', city: 'Sargodha'),
      RailwayStation(name: 'Piaro Goth', code: 'PGT', city: 'Sindh'),
      RailwayStation(name: 'Pind Dadan Khan', code: 'PDK', city: 'Jhelum'),
      RailwayStation(name: 'Pind Mukkho', code: 'PMK', city: 'Punjab'),
      RailwayStation(name: 'Piplan', code: 'PPL', city: 'Mianwali'),
      RailwayStation(name: 'Pir Mahal', code: 'PMH', city: 'Toba Tek Singh'),
      RailwayStation(name: 'Qaidabad', code: 'QDB', city: 'Khushab'),
      RailwayStation(
          name: 'Qila Sheikhupura', code: 'QLS', city: 'Sheikhupura'),
      RailwayStation(name: 'Qila Sobha Singh', code: 'QSS', city: 'Narowal'),
      RailwayStation(name: 'Quetta', code: 'QTA', city: 'Quetta'),
      RailwayStation(name: 'Quetta Cantt.', code: 'QTC', city: 'Quetta'),
      RailwayStation(name: 'Radhan', code: 'RDN', city: 'Punjab'),
      RailwayStation(name: 'Rahimabad', code: 'RMB', city: 'Punjab'),
      RailwayStation(
          name: 'Rahim Yar Khan', code: 'RYK', city: 'Rahim Yar Khan'),
      RailwayStation(name: 'Raiwind Jn.', code: 'RWD', city: 'Lahore'),
      RailwayStation(name: 'Rajanpur', code: 'RJP', city: 'Rajanpur'),
      RailwayStation(name: 'Ran Pethani', code: 'RPN', city: 'Sindh'),
      RailwayStation(name: 'Ranipur', code: 'RNP', city: 'Sindh'),
      RailwayStation(name: 'Rashidabad', code: 'RSB', city: 'Sindh'),
      RailwayStation(name: 'Ratto Kala', code: 'RTK', city: 'Gujranwala'),
      RailwayStation(name: 'Rawalpindi', code: 'RWP', city: 'Rawalpindi'),
      RailwayStation(name: 'Raya Khas', code: 'RKS', city: 'Punjab'),
      RailwayStation(name: 'Rehmani Nagar', code: 'RMN', city: 'Punjab'),
      RailwayStation(name: 'Rohri Jn.', code: 'RHR', city: 'Sukkur'),
      RailwayStation(name: 'Ruk', code: 'RUK', city: 'Sindh'),
      RailwayStation(name: 'Rurala Road', code: 'RRL', city: 'Faisalabad'),
      RailwayStation(name: 'Sadikabad', code: 'SDB', city: 'Rahim Yar Khan'),
      RailwayStation(name: 'Safdarabad', code: 'SFD', city: 'Sheikhupura'),
      RailwayStation(name: 'Sahiwal', code: 'SWL', city: 'Sahiwal'),
      RailwayStation(name: 'Sambrial', code: 'SBR', city: 'Sialkot'),
      RailwayStation(name: 'Samasata Jn.', code: 'SMT', city: 'Bahawalpur'),
      RailwayStation(name: 'Sani Ghumabat', code: 'SNG', city: 'Punjab'),
      RailwayStation(name: 'Sanawan', code: 'SNW', city: 'Punjab'),
      RailwayStation(name: 'Sangla Hill', code: 'SGL', city: 'Nankana Sahib'),
      RailwayStation(name: 'Sara-E-Saleh', code: 'SRS', city: 'Punjab'),
      RailwayStation(name: 'Sarhari', code: 'SAH', city: 'Punjab'),
      RailwayStation(name: 'Sargodha Jn.', code: 'SGD', city: 'Sargodha'),
      RailwayStation(name: 'Sehwan Sharif', code: 'SWN', city: 'Jamshoro'),
      RailwayStation(name: 'Sethraja', code: 'STR', city: 'Punjab'),
      RailwayStation(name: 'Shah Nawaz Bhutto', code: 'SNB', city: 'Larkana'),
      RailwayStation(name: 'Shahalam', code: 'SHM', city: 'Lahore'),
      RailwayStation(name: 'Shahdadpur', code: 'SDP', city: 'Sanghar'),
      RailwayStation(name: 'Shahdara Bagh', code: 'SHB', city: 'Lahore'),
      RailwayStation(name: 'Shahinabad Jn.', code: 'SNJ', city: 'Multan'),
      RailwayStation(name: 'Shadan Lund', code: 'SHL', city: 'Punjab'),
      RailwayStation(name: 'Shekhmanda', code: 'SKD', city: 'Balochistan'),
      RailwayStation(name: 'Shelabagh', code: 'SLG', city: 'Killa Abdullah'),
      RailwayStation(name: 'Sharig', code: 'SHG', city: 'Balochistan'),
      RailwayStation(name: 'Shershahjn.', code: 'SSJ', city: 'Punjab'),
      RailwayStation(name: 'Shikarpur', code: 'SKP', city: 'Shikarpur'),
      RailwayStation(name: 'Shorkot Cantt Jn.', code: 'SCJ', city: 'Jhang'),
      RailwayStation(name: 'Shujabad', code: 'SJB', city: 'Multan'),
      RailwayStation(name: 'Sialkot Jn.', code: 'SKT', city: 'Sialkot'),
      RailwayStation(name: 'Sibi Jn.', code: 'SBI', city: 'Sibi'),
      RailwayStation(name: 'Sihar', code: 'SHR', city: 'Sindh'),
      RailwayStation(name: 'Sillanwali', code: 'SLW', city: 'Sargodha'),
      RailwayStation(name: 'Sind University', code: 'SNU', city: 'Jamshoro'),
      RailwayStation(name: 'Sodhra Kopra', code: 'SKO', city: 'Gujranwala'),
      RailwayStation(name: 'Sohawa', code: 'SHW', city: 'Jhelum'),
      RailwayStation(name: 'Spintangi', code: 'SPT', city: 'Balochistan'),
      RailwayStation(name: 'Srirampura', code: 'SRP', city: 'Punjab'),
      RailwayStation(name: 'Sukheke', code: 'SKE', city: 'Hafizabad'),
      RailwayStation(name: 'Sukkur', code: 'SKR', city: 'Sukkur'),
      RailwayStation(name: 'Sulemanabad', code: 'SLB', city: 'KPK'),
      RailwayStation(name: 'Sunehri', code: 'SNH', city: 'Balochistan'),
      RailwayStation(name: 'Tandliawala', code: 'TLW', city: 'Faisalabad'),
      RailwayStation(name: 'Tando Adam', code: 'TDA', city: 'Sanghar'),
      RailwayStation(name: 'Tando Allah Yar', code: 'TAY', city: 'Hyderabad'),
      RailwayStation(name: 'Tando Jam', code: 'TJM', city: 'Hyderabad'),
      RailwayStation(name: 'Tarnol', code: 'TRN', city: 'Islamabad'),
      RailwayStation(
          name: 'Taunsabarrage', code: 'TNB', city: 'Dera Ghazi Khan'),
      RailwayStation(name: 'Taxila', code: 'TXL', city: 'Rawalpindi'),
      RailwayStation(
          name: 'Toba Tek Singh', code: 'TTS', city: 'Toba Tek Singh'),
      RailwayStation(name: 'Uchhri', code: 'UCH', city: 'Bahawalpur'),
      RailwayStation(name: 'Ugoke', code: 'UGK', city: 'Sargodha'),
      RailwayStation(name: 'Usman Khattar', code: 'UKT', city: 'KPK'),
      RailwayStation(name: 'Usmanwala', code: 'USW', city: 'Kasur'),
      RailwayStation(name: 'Vihari', code: 'VHR', city: 'Vehari'),
      RailwayStation(name: 'Wah', code: 'WAH', city: 'Attock'),
      RailwayStation(name: 'Walton', code: 'WLT', city: 'Lahore'),
      RailwayStation(name: 'Wan Bhachran', code: 'WBN', city: 'Mianwali'),
      RailwayStation(name: 'Warburton', code: 'WBT', city: 'Nankana Sahib'),
      RailwayStation(name: 'Wazirabad Jn.', code: 'WZB', city: 'Wazirabad'),
      RailwayStation(name: 'Yaru', code: 'YRU', city: 'Killa Abdullah'),
      RailwayStation(name: 'Zarif Shahid', code: 'ZRS', city: 'Punjab'),
    ];
  }
}
